version: 2
updates:
  - package-ecosystem: npm
    directory: /
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    target-branch: develop
=======
>>>>>>> ece89de (Fix/dependencies error (#6))
=======
    target-branch: develop
>>>>>>> f80b59b (Fix/dependencies error (#7))
=======
    target-branch: develop
>>>>>>> e0c3519b3bde3e38da38e17dbae1b018472f1c82
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: America/New_York
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
    labels:
      - dependencies
      - security
  - package-ecosystem: github-actions
    directory: /
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    target-branch: develop
=======
>>>>>>> ece89de (Fix/dependencies error (#6))
=======
    target-branch: develop
>>>>>>> f80b59b (Fix/dependencies error (#7))
=======
    target-branch: develop
>>>>>>> e0c3519b3bde3e38da38e17dbae1b018472f1c82
    schedule:
      interval: weekly
      day: monday
      time: "07:30"
      timezone: America/New_York
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
      - security
